export const GET_ERRORS= "GET_ERRORS"
export const GET_SERVICES= "GET_SERVICES"
export const GET_WALLET_DETAILS= "GET_WALLET_DETAILS"
export const GET_FUNDING_ERRORS= "GET_FUNDING_ERRORS"
export const GET_SERVICE_REQUEST_RESPONSE="GET_SERVICE_REQUEST_RESPONSE"
export const GET_REGISTRATION_ERROR="REGISTRATION_ERROR"
export const SET_CURRENT_USER= "SET_CURRENT_USER"

